# Generated by Django 5.2.5 on 2025-08-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the bill', max_length=150)),
                ('number', models.CharField(help_text='Title of the bill', max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
                'default_related_name': 'bills',
            },
        ),
    ]
