# Generated by Django 5.2.5 on 2025-08-12 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'default_related_name': 'clients',
            },
        ),
        migrations.CreateModel(
            name='ClientBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_relation', models.DateField(auto_now_add=True, help_text='Date of relation')),
                ('priority', models.IntegerField(default=3)),
                ('bill', models.ForeignKey(help_text='Bill', on_delete=django.db.models.deletion.CASCADE, to='bills.bill')),
                ('client', models.ForeignKey(help_text='Client', on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
            options={
                'verbose_name': 'ClientBill',
                'verbose_name_plural': 'ClientBills',
                'default_related_name': 'clientbills',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='bills',
            field=models.ManyToManyField(help_text='Bills', through='clients.ClientBill', to='bills.bill'),
        ),
    ]
